### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3]) #vector
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #Matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #Tensor
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# dtype

np.array([1,2,3], dtype=np.float64)

array([1., 2., 3.])

In [12]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [13]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
# np.range same as oython range but it returns an array instead of a list

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

c.reshape(3,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
# np.ones and np.zeros

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# np.random

np.random.random((2,3))

array([[0.45520804, 0.3484257 , 0.66495229],
       [0.59110599, 0.93602909, 0.61979166]])

In [25]:
# np.linspace - will create an array of evenly spaced numbers over a specified interval.

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
# np.identity - will create an identity matrix  - that is a square matrix with ones on the main diagonal and zeros elsewhere.

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [28]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [29]:
# ndim

a3.ndim

3

In [32]:
# shape

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
# Size

print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [34]:
# itemsize - har item memeory mai kitna size occupy kar raha hai 

a3.itemsize

8

In [35]:
a2.itemsize

8

# Changing Datatype

In [36]:
# astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [37]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# arithmetic

a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [41]:
# relational

a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a1 ** 2 > 5

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
# vector operations
# arithmetic

a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [48]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[78., 20., 72.],
       [57., 65., 37.],
       [22., 75., 90.]])

In [50]:
# ma/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

90.0
20.0
516.0
2286511999200000.0


In [51]:
# 0 -> col, 1 -> row, 2 -> depth

np.max(a1, axis=0)

array([78., 75., 90.])

In [52]:
np.max(a1, axis=1)

array([78., 65., 90.])

In [54]:
# mean/median/std/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

57.333333333333336
65.0
23.888630489558555
570.6666666666666


In [55]:
# trigonometric functions

np.sin(a1)

array([[ 0.51397846,  0.91294525,  0.25382336],
       [ 0.43616476,  0.82682868, -0.64353813],
       [-0.00885131, -0.38778164,  0.89399666]])

In [59]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [61]:
# log and exponents

print(np.log(a1))
print(np.exp(a1))

[[4.35670883 2.99573227 4.27666612]
 [4.04305127 4.17438727 3.61091791]
 [3.09104245 4.31748811 4.49980967]]
[[7.49841700e+33 4.85165195e+08 1.85867175e+31]
 [5.68572000e+24 1.69488924e+28 1.17191424e+16]
 [3.58491285e+09 3.73324200e+32 1.22040329e+39]]


In [70]:
# round/floor/ceil

np.round(np.random.random((2,3)))*100

array([[100.,   0.,   0.],
       [100., 100., 100.]])

In [69]:
np.ceil(np.random.random((2,3)))*100

array([[100., 100., 100.],
       [100., 100., 100.]])

In [71]:
np.floor(np.random.random((2,3)))*100

array([[0., 0., 0.],
       [0., 0., 0.]])

# Indexing and Slicing

In [72]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [74]:
a1[-1]

np.int64(9)

In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[1][2]

np.int64(6)

In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
a3[1][0][1]

np.int64(5)

In [79]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1[2:5]

array([2, 3, 4])

In [83]:
a1[2:8:2]

array([2, 4, 6])

In [84]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a2[1,:]

array([4, 5, 6, 7])

In [87]:
a2[:,2]

array([ 2,  6, 10])

In [88]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [89]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [90]:
a2[1,::3]

array([4, 7])

In [94]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [97]:
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [102]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Iterating

In [103]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [107]:
a2 

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [108]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [109]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
