# Compare Numpy Array vs Python List

In [3]:
import numpy as np

In [1]:
import time 

a = [i for i in range(100000000)]
b = [i for i in range(100000000, 200000000)]

c = []

start_time = time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])

time.time() - start_time    

107.43318748474121

In [ ]:
import numpy as np
a = np.arange(100000000)
b = np.arange(100000000, 200000000)

c = []

start_time = time.time()

c = a+b

time.time() - start_time   

In [1]:
# Memory
import sys
a = [i for i in range(100000000)]

sys.getsizeof(a)

835128600

# Normal Indexing and Slicing

In [11]:
a = np.arange(24).reshape(6,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a[1][2]

np.int64(5)

In [7]:
a[1:3, 2:4]

array([[ 6,  7],
       [10, 11]])

In [12]:
# Fancy Indexing

a[[0,3,4]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [16]:
# Boolean Indexing

a = np.random.randint(1,100,24).reshape(6,4)

a

array([[ 9, 78, 41, 24],
       [20, 30, 42, 60],
       [70, 56, 35, 14],
       [47, 26, 21, 47],
       [19, 33,  6, 34],
       [75, 64, 94, 34]], dtype=int32)

In [17]:
# Find all the values which are greater than 50

a > 50

array([[False,  True, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True, False]])

In [19]:
a[a>50]

array([78, 60, 70, 56, 75, 64, 94], dtype=int32)

In [20]:
# Lets find out all the even numbers from a

a%2 == 0

array([[False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

In [21]:
a[ a%2 == 0 ]

array([78, 24, 20, 30, 42, 60, 70, 56, 14, 26,  6, 34, 64, 94, 34],
      dtype=int32)

In [25]:
# Find all the values which are greater than 50 and are even

a[(a > 50) & (a%2 == 0)]

array([78, 60, 70, 56, 64, 94], dtype=int32)

In [27]:
# Find all the numbers that are divisible by 7

a[a%7 == 0]

array([42, 70, 56, 35, 14, 21], dtype=int32)

In [28]:
# Find all the numbers that are not divisible by 7

a[(~(a%7 == 0))]

array([ 9, 78, 41, 24, 20, 30, 60, 47, 26, 47, 19, 33,  6, 34, 75, 64, 94,
       34], dtype=int32)

# Broadcasting

In [32]:
# broadcasting - it is a powerful mechanism that allows numpy to perform operations 
# on arrays of different shapes and sizes without the need for explicit loops or copying of data. 
# It works by automatically expanding the smaller array to match the shape of the larger array, 
# allowing for element-wise operations to be performed seamlessly.

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


Two conditions we need to see here 

1. there should be 1 to extend it , then only it will happen (3,4), (1,4) == Yes, but (2,2) , (4,4) == No
2. First we make the smaller one extend to the larger one

In [33]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [36]:
a = np.arange(12).reshape(4,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
