np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[48, 40, 92, 73],
       [92, 31, 29, 29],
       [92, 11, 51, 46],
       [34, 87, 45, 43],
       [33, 13, 74, 33],
       [36, 48, 71, 48]], dtype=int32)

In [4]:
np.sort(a)

array([ 2,  5, 14, 18, 29, 30, 37, 40, 41, 51, 53, 82, 83, 88, 92],
      dtype=int32)

In [5]:
np.sort(a)[::-1]

array([92, 88, 83, 82, 53, 51, 41, 40, 37, 30, 29, 18, 14,  5,  2],
      dtype=int32)

In [6]:
# Row wise sorting
np.sort(b, axis=1)

array([[40, 48, 73, 92],
       [29, 29, 31, 92],
       [11, 46, 51, 92],
       [34, 43, 45, 87],
       [13, 33, 33, 74],
       [36, 48, 48, 71]], dtype=int32)

In [7]:
# Column wise sorting
np.sort(b, axis=0)

array([[33, 11, 29, 29],
       [34, 13, 45, 33],
       [36, 31, 51, 43],
       [48, 40, 71, 46],
       [92, 48, 74, 48],
       [92, 87, 92, 73]], dtype=int32)

np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code

np.append(a, 100)

array([ 29,  92,  51,  88,  18,  40,  82,  83,  53,  41,  30,   2,   5,
        14,  37, 100])

In [9]:
b

array([[48, 40, 92, 73],
       [92, 31, 29, 29],
       [92, 11, 51, 46],
       [34, 87, 45, 43],
       [33, 13, 74, 33],
       [36, 48, 71, 48]], dtype=int32)

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[48., 40., 92., 73.,  1.],
       [92., 31., 29., 29.,  1.],
       [92., 11., 51., 46.,  1.],
       [34., 87., 45., 43.,  1.],
       [33., 13., 74., 33.,  1.],
       [36., 48., 71., 48.,  1.]])

In [15]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[48.        , 40.        , 92.        , 73.        ,  0.55462755],
       [92.        , 31.        , 29.        , 29.        ,  0.41910798],
       [92.        , 11.        , 51.        , 46.        ,  0.28973861],
       [34.        , 87.        , 45.        , 43.        ,  0.90915934],
       [33.        , 13.        , 74.        , 33.        ,  0.22068234],
       [36.        , 48.        , 71.        , 48.        ,  0.90548298]])

np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d), axis=0) # row wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d), axis=1) # column wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [19]:
# code

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [21]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [22]:
np.expand_dims(a, axis=0) # row vector

array([[29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37]],
      dtype=int32)

In [ ]:
np.expand_dims(a, axis=1) # column vector used in machine learning algorithms and deep learning algorithms

array([[29],
       [92],
       [51],
       [88],
       [18],
       [40],
       [82],
       [83],
       [53],
       [41],
       [30],
       [ 2],
       [ 5],
       [14],
       [37]], dtype=int32)

np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [25]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [26]:
# find all indices with  value greater than 50

indices = np.where(a>50)
indices

(array([1, 2, 3, 6, 7, 8]),)

In [ ]:
# replace all values > 50 with 0

# np.where(condition, value if condition is true, value if condition is false)

np.where(a>50, 0, a)

array([29,  0,  0,  0, 18, 40,  0,  0,  0, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [28]:
np.where(a%2 == 0,0,a)

array([29,  0, 51,  0,  0,  0,  0, 83, 53, 41,  0,  0,  5,  0, 37],
      dtype=int32)

np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [29]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [30]:
np.argmax(a) # index of maximum value in the array

np.int64(1)

In [31]:
np.argmin(a) # index of minimum value in the array

np.int64(11)

In [32]:
b

array([[48, 40, 92, 73],
       [92, 31, 29, 29],
       [92, 11, 51, 46],
       [34, 87, 45, 43],
       [33, 13, 74, 33],
       [36, 48, 71, 48]], dtype=int32)

In [33]:
np.argmax(b, axis=0) # index of maximum value in each column

array([1, 3, 0, 0])

In [34]:
np.argmax(b, axis=1) # index of maximum value in each row

array([2, 0, 0, 1, 2, 2])

np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [35]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [36]:
np.cumsum(a) # cumulative sum of the array

array([ 29, 121, 172, 260, 278, 318, 400, 483, 536, 577, 607, 609, 614,
       628, 665])

In [37]:
b

array([[48, 40, 92, 73],
       [92, 31, 29, 29],
       [92, 11, 51, 46],
       [34, 87, 45, 43],
       [33, 13, 74, 33],
       [36, 48, 71, 48]], dtype=int32)

In [ ]:
np.cumsum(b,axis=1) # cumulative sum of each row

array([[ 48,  88, 180, 253],
       [ 92, 123, 152, 181],
       [ 92, 103, 154, 200],
       [ 34, 121, 166, 209],
       [ 33,  46, 120, 153],
       [ 36,  84, 155, 203]])

In [40]:
np.cumsum(b, axis=0) # cumulative sum of each column

array([[ 48,  40,  92,  73],
       [140,  71, 121, 102],
       [232,  82, 172, 148],
       [266, 169, 217, 191],
       [299, 182, 291, 224],
       [335, 230, 362, 272]])

In [41]:
np.cumprod(a)

array([                 29,                2668,              136068,
                  11973984,           215531712,          8621268480,
              706944015360,      58676353274880,    3109846723568640,
        127503715666314240, 3825111469989427200, 7650222939978854400,
       1357626552475168768,  560027660942811136, 2274279381174460416])

np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [42]:
np.percentile(a,100)

np.float64(92.0)

In [43]:
np.percentile(a, 0) # 25th percentile

np.float64(2.0)

In [44]:
np.percentile(a, 50)

np.float64(40.0)

In [45]:
np.median(a)

np.float64(40.0)

np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [46]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [48]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 2, 2, 2, 0, 0, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [50]:
np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [51]:
# search multiple values in an array
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [54]:
items = [10,20,30]

np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [55]:
a[np.isin(a, items)]

array([30], dtype=int32)

np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [56]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [57]:
np.flip(a)

array([37, 14,  5,  2, 30, 41, 53, 83, 82, 40, 18, 88, 51, 92, 29],
      dtype=int32)

In [58]:
b

array([[48, 40, 92, 73],
       [92, 31, 29, 29],
       [92, 11, 51, 46],
       [34, 87, 45, 43],
       [33, 13, 74, 33],
       [36, 48, 71, 48]], dtype=int32)

In [59]:
np.flip(b)

array([[48, 71, 48, 36],
       [33, 74, 13, 33],
       [43, 45, 87, 34],
       [46, 51, 11, 92],
       [29, 29, 31, 92],
       [73, 92, 40, 48]], dtype=int32)

In [60]:
np.flip(b, axis=0) # flip rows

array([[36, 48, 71, 48],
       [33, 13, 74, 33],
       [34, 87, 45, 43],
       [92, 11, 51, 46],
       [92, 31, 29, 29],
       [48, 40, 92, 73]], dtype=int32)

In [61]:
np.flip(b, axis=1) # flip column

array([[73, 92, 40, 48],
       [29, 29, 31, 92],
       [46, 51, 11, 92],
       [43, 45, 87, 34],
       [33, 74, 13, 33],
       [48, 71, 48, 36]], dtype=int32)

np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [62]:
a

array([29, 92, 51, 88, 18, 40, 82, 83, 53, 41, 30,  2,  5, 14, 37],
      dtype=int32)

In [ ]:
np.put(a, [0,1], [110,530]) # this can be continuous or non continuous indices

In [64]:
a

array([110, 530,  51,  88,  18,  40,  82,  83,  53,  41,  30,   2,   5,
        14,  37], dtype=int32)

np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [65]:
a

array([110, 530,  51,  88,  18,  40,  82,  83,  53,  41,  30,   2,   5,
        14,  37], dtype=int32)

In [67]:
np.delete(a, [0,4,8]) # this can be continuous or non continuous indices

array([530,  51,  88,  40,  82,  83,  41,  30,   2,   5,  14,  37],
      dtype=int32)

Set functions
np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

In [68]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n) # a mai hai , b mai nahi hai 

array([1, 2])

In [ ]:
np.setxor1d(m,n) # remove common one keep else

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,1) # value nikalne ka tareeka

C:\Users\Sanjog Bhalla\AppData\Local\Temp\ipykernel_17748\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])